TRUNCATE TABLE BNR_STVCODE;
INSERT INTO BNR_STVCODE
  (
    STVCODE_TABLE,
    STVCODE_CODE,
    STVCODE_DESC
  )
SELECT 'STVCOLL' AS STVCODE_TABLE, STVCOLL_CODE AS STVCODE_CODE, STVCOLL_DESC AS STVCODE_DESC FROM STVCOLL@EDW_BANNER_LINK UNION
SELECT 'STVDEPT' AS STVCODE_TABLE, STVDEPT_CODE AS STVCODE_CODE, STVDEPT_DESC AS STVCODE_DESC FROM STVDEPT@EDW_BANNER_LINK UNION
SELECT 'STVDEGC' AS STVCODE_TABLE, STVDEGC_CODE AS STVCODE_CODE, STVDEGC_DESC AS STVCODE_DESC FROM STVDEGC@EDW_BANNER_LINK UNION
SELECT 'STVMAJR' AS STVCODE_TABLE, STVMAJR_CODE AS STVCODE_CODE, STVMAJR_DESC AS STVCODE_DESC FROM STVMAJR@EDW_BANNER_LINK UNION
SELECT 'STVLEVL' AS STVCODE_TABLE, STVLEVL_CODE AS STVCODE_CODE, STVLEVL_DESC AS STVCODE_DESC FROM STVLEVL@EDW_BANNER_LINK UNION
SELECT 'STVSTYP' AS STVCODE_TABLE, STVSTYP_CODE AS STVCODE_CODE, STVSTYP_DESC AS STVCODE_DESC FROM STVSTYP@EDW_BANNER_LINK UNION
SELECT 'STVCAMP' AS STVCODE_TABLE, STVCAMP_CODE AS STVCODE_CODE, STVCAMP_DESC AS STVCODE_DESC FROM STVCAMP@EDW_BANNER_LINK UNION
SELECT 'USGRGNT' AS STVCODE_TABLE, '10' AS STVCODE_CODE, 'Freshman'            AS STVCODE_DESC FROM DUAL UNION
SELECT 'USGRGNT' AS STVCODE_TABLE, '20' AS STVCODE_CODE, 'Sophomore'           AS STVCODE_DESC FROM DUAL UNION
SELECT 'USGRGNT' AS STVCODE_TABLE, '30' AS STVCODE_CODE, 'Junior'              AS STVCODE_DESC FROM DUAL UNION
SELECT 'USGRGNT' AS STVCODE_TABLE, '40' AS STVCODE_CODE, 'Senior'              AS STVCODE_DESC FROM DUAL UNION
SELECT 'USGRGNT' AS STVCODE_TABLE, '60' AS STVCODE_CODE, 'Non Degree Graduate' AS STVCODE_DESC FROM DUAL UNION
SELECT 'USGRGNT' AS STVCODE_TABLE, '70' AS STVCODE_CODE, 'Graduate'            AS STVCODE_DESC FROM DUAL
ORDER BY
  STVCODE_TABLE,
  STVCODE_CODE
;

COMMIT;

QUIT;
